In [3]:
%pip install pandas matplotlib

Requirement already satisfied: pandas in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (3.0.5)
Requirement already satisfied: matplotlib in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (3.11.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3-pbe/envs/fe-course/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
## numpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
big_array = np.arange(1000000)
%timeit big_array * 2

1.17 ms ± 50 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [8]:
big_list = list(range(1000000))
%timeit [x * 2 for x in big_list]

34.1 ms ± 2.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [24]:
## dataset load
df = pd.read_csv("../data/raw/starter_data.csv")
df

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05
5        C     30  2025-08-06
6        A     11  2025-08-07
7        B     14  2025-08-08
8        C     28  2025-08-09
9        A     13  2025-08-10

In [10]:
df.head()

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     str
 1   value     10 non-null     int64
 2   date      10 non-null     str
dtypes: int64(1), str(2)
memory usage: 372.0 bytes

In [12]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     str
 1   value     10 non-null     int64
 2   date      10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 372.0 bytes

In [26]:
## stat summary
df.groupby("category")["value"].mean()

category
A    11.500000
B    15.666667
C    27.666667
Name: value, dtype: float64

In [16]:
df.describe()

           value                 date
count  10.000000                   10
mean   17.600000  2025-08-05 12:00:00
min    10.000000  2025-08-01 00:00:00
25%    12.250000  2025-08-03 06:00:00
50%    14.500000  2025-08-05 12:00:00
75%    23.250000  2025-08-07 18:00:00
max    30.000000  2025-08-10 00:00:00
std     7.381659                  NaN

In [27]:
## save output
from pathlib import Path
Path("../data/processed").mkdir(parents=True, exist_ok=True)

In [25]:
summary = df.describe()
summary.to_csv("../data/processed/summary.csv")

In [28]:
## reusable func
def get_category_summary(df):
    return df.groupby("category")["value"].mean()

In [21]:
get_category_summary(df)

category
A    11.500000
B    15.666667
C    27.666667
Name: value, dtype: float64